### PR TITLE
Define feature macros only on Linux

### PR DESCRIPTION
**Pull request by mazocomp**

### CODE REVIEW

**Comment by mazocomp** [comment]
https://github.com/cylgom/termbox-next/pull/1

**Comment by iamleot** [comment]
Hello Leonid,

Leonid Bobrov writes:
> [...]
>   * Define feature macros only on Linux
> [...]

Why? (at least -D_XOPEN_SOURCE but probably also -D__BSD_VISIBLE
is honored by other operating systems as well)

**Comment by mazocomp** [comment]
@iamleot Hi.

Take a look at link above: it refuses to compile at *BSD (I am running DragonFly BSD).

Also any macro starting with __ is not supposed to be used by Makefile, so having __BSD_VISIBLE as a flag is a bug (try _BSD_SOURCE instead), but I care about compilation at *BSD and Linux, I can't test at other OSes.

**Comment by iamleot** [comment]
Leonid Bobrov writes:
> [...]
> Take a look at link above: it refuses to compile at *BSD (I am running DragonFly BSD).
>
> Also any macro starting with __ is not supposed to be used by Makefile, so having __BSD_VISIBLE as a flag is a bug (try _BSD_SOURCE instead), but I care about compilation at *BSD and Linux, I can't test at other OSes.
> [...]

AFAIK only FreeBSD and DragonFly BSD has that behaviour.
It is probably safer to conditionally remove the CPPFLAGS only for
them instead of enabling them only for Linux.

**Comment by mazocomp** [comment]
@imleot Does the current diff look ok? I don't know how GNU make works, so I am sorry for possible mistake.

**Comment by iamleot** [comment]
Leonid Bobrov writes:
> @imleot Does the current diff look ok? I don't know how GNU make works, so I am sorry for possible mistake.

I think that the ifneq should be replaced with something like that:

    ifeq "$(findstring $(OS),FreeBSD DragonFly)" ""
    ...
    endif


(Also, if possible it is usually better to add a rationale in the
commit message (why a change is needed), but beware!, I'm not a
vimb developer! :))


Thank you!

**Comment by fanglingsu** [comment]
@mazocomp Both defines where added to get rid of FreeBSD compile errors #76. So I think your patch should work also on gnu systems.

**Comment by mazocomp** [comment]
@fanglingsu my patch works for both FreeBSD and DragonFly BSD (note that Vimb failed to compile at DragonFly BSD without this patch), I didn't test it at OpenBSD and NetBSD yet, but it should work there too. And remember: It's a bug to define macros in compiler which start with __, also please see the first link I sent in this PR: 
https://github.com/cylgom/termbox-next/pull/1

**Pull request merged**
