### PR TITLE
improve hint char selection

### PR DESCRIPTION
**Pull request by rti**
Improves the hint char selection, especially for ```hint-keys``` settings other than the default (e.g. ```set hint-keys=asdfg;lkjh``` as suggested in the man page)

### Before
Until now the ```hint-keys``` string was used in a way that the default ```0123456789``` string generated nice decimal numbers as expected: ```1 2 3 4 5 6 7 8 9 10 11 12 13 14 15```

But setting it to something different, such as ```12345```, if you want to use only the left hand to select hints, generated somewhat strange results: ```2 3 4 5 21 22 23 24 25 31 32 33 34 35 41``` 

Same happened with the suggested home row setting from the man page: ```s d f g ; l k j h sa ss sd sf sg s;```

The first char, the ```1``` or ```a``` was never used as a leading hint character. This actually wasted it and created unnecessarily long hints.

### This patch
- Makes use of the first character as a leading hint char as well
- Therefore creates somewhat shorter hint strings
- Stays very close to the default behaviour when using the default ```hint-keys``` setting

#### The new default 1234567890
```1 2 3 4 5 6 7 8 9 0 11 12 13 14 15``` 

#### Left hand mode 12345
```1 2 3 4 5 11 12 13 14 15 21 22 23 24 25```

#### Home row mode asdfg;lkjh
```a s d f g ; l k j h aa as ad af ag```

### CODE REVIEW

**Comment by rti** [comment]
Just realized, this patch breakes ```set hint-number-same-length=true```.
So it should be considered work in progress atm. Sorry for the noise.

**Comment by fanglingsu** [comment]
@rti Thank you! Nice investigation - this is a pretty nice patch. I'll keep it open as long as the `hint-number-same-length` does not work. So we can merge a working state.

**Comment by fanglingsu** [comment]
@rti Do you still work on this, or should I try to fix the hint-number-same-length issue?

**Comment by rti** [comment]
@fanglingsu Still working on it. Patch is almost ready. Just a limited amount of time on my side.  ETA before next week.

**Comment by fanglingsu** [comment]
@rti Ok! I'm looking forward.

**Comment by rti** [comment]
@fanglingsu If you are very curious, I am working on it over here https://github.com/fanglingsu/vimb/compare/master...rti:improve_hint_char_selection_wip

**Comment by fanglingsu** [comment]
@rti Nice with manual test case. I think you don't need to link to a real page in the test you can link to the file itself `href="./"` or `href="#{num}"` in case your are interested if the hint was fired properly.

**Comment by rti** [comment]
Ah yes. Good point.

**Comment by rti** [comment]
Do you want the test case included in the merge request?

**Comment by fanglingsu** [comment]
Yes, having the test would be nice and we can modify it later to test other aspects of the hinting too. I think it's a good decision to have some test pages we can refern too in case of bugs.

**Comment by rti** [comment]
Ok, what I initially thought to be an off-by-one error turned out to be a bit more complex than expected. Anyway. Here it is now.

**Comment by fanglingsu** [comment]
In case the default hint keys are used the 10th hint becomes the label '0' instead of the natural '10', do you have any idea hove we can also get nice decimal numbering `1 2 3 4 5 6 7 8 9 10 11`?

**Comment by fanglingsu** [comment]
I've shortened some of the variabled because the JS is compiled into vimb so we should try to kepp it short until we can shorten minify it automatically.

**Pull request merged**
