### PR TITLE
Improve scripts change detection in Makefile

### PR DESCRIPTION
**Pull request by hsoft**
When changing a script in `src/scripts`, `make` would need to be invoked
twice for a proper build: once for `scripts.h` and once for the `.o`
files depending on it.

This commit fixes this by always calling `scripts.subdir-all`.

### CODE REVIEW

**Comment by fanglingsu** [comment]
@hsoft Nice investigation. But ordering the requirements for the target 'all' does not properly work, as you can see on the travis build. If Make is called to run in parallel. So I think we have to write the dependencies explicitly.

**Comment by hsoft** [comment]
Hum, yes, I see. Will try to fix later today.

**Comment by fanglingsu** [comment]
Maybe it was a bad decision of me to implement the Makefile in each directory separate not concerning possible dependencies between compilation target built in one directory but required in another one.

**Comment by hsoft** [comment]
After some messing around, I could indeed not manage to fix the issue without removing the recursive `make` call for `src/scripts`. This commit fixes the problem, but I don't know how you feel about removing `src/scripts/Makefile`. Sure, it introduces an inconsistency in the makefiles, but it also fixes a real problem.

**Comment by fanglingsu** [comment]
@hsoft Thank you for the patch. Now it's better - the `scripts` directory is only to keep the `src` directory neat. But the sources in `scripts` are only to generate dependencies for thins done in `src`. I think we can write the `script.h` file into `src` later.

**Pull request merged**
