### PR TITLE
Add simple *.desktop file

### PR DESCRIPTION
**Pull request by parnmatt**
A Desktop file was lacking. This is a quick version that does the job.

### CODE REVIEW

**Comment by rti** [comment]
Another one is also over here https://github.com/fanglingsu/vimb/blob/webkit2/vimb.desktop

Maybe they could be merged?

**Comment by parnmatt** [comment]
I'm sure they can; I was just unsure of the exact protocols that vimb does use other than html.
I will update this request with a desktop file containing the relevant information from both

**Comment by rti** [comment]
Thanks a lot. Nice to have them synced.

**Comment by parnmatt** [comment]
👍

**Comment by fanglingsu** [comment]
Sorry for the late merge and thank you for your work!

**Pull request merged**
