### PR TITLE
Small changes to build on OSX with macports

### PR DESCRIPTION
**Pull request by plredmond**
I built vimb on OSX Mavericks.

Steps to repro:

1. Install [macports](https://www.macports.org/install.php). Take note of the prefix (default is `/opt/local`).
1. Install vimb dependencies `sudo port install webkit-gtk3`. This takes hours.
1. Check out `vimb` https://github.com/fanglingsu/vimb/commit/c5b20658e84ae96c9945c1ca328813df8163aecc (last commit before switching to flock locking).
1. Apply the very small patch in this PR.
1. Build by telling `pkg-config` where to find the `vimb` dependencies:

    ```sh
    env PKG_CONFIG_PATH=${MACPORTS_PREFIX?}/lib/pkgconfig make
    ```

    If you have trouble with the library version conditional logic in `config.mk`, apply [this patch](https://gist.github.com/plredmond/c57bed437da15de6e4e5).
1. Feel vimb zen.

screen shot 2015-11-17 at 10 50 44

### CODE REVIEW

**Comment by plredmond** [comment]
A prerequisite for merging this PR might be fixing the conditional logic in `config.mk`. I'm not sure how to debug things in `make`, though.

**Comment by fanglingsu** [comment]
Thank you for the patch. Looks good.

**Comment by dan2** [comment]
Can confirm that this works in Yosemite as well.  (am posting this comment from vimb)

It does run very slowly, though.  Any thoughts on how to speed things up?

**Comment by dan2** [comment]
Scratch that -- it isn't slow; the screen isn't updating.  I''m running vimb inside tabbed and if I switch from one tab and back to the previous, vimb has responded to my commands

**Comment by plredmond** [comment]
I encountered the same issue. What versions of WebKit and gtk did you
compile with?

**Comment by dan2** [comment]
gtk3 @3.20.3_0+x11
webkit-gtk3 @2.4.11_0+video

Installed both via macports

**Comment by fanglingsu** [comment]
@dan2 I think that's the same issue as #138. But we don't know what's the reason for that. It seems to be some strange corner case between gtk3 and tabbed. You have two options here, compile against gtk2 or run without tabbed.

**Comment by plredmond** [comment]
Despite my instructions to apply a patch in step 5 of the opening post for this PR, I think I worked around the "slow rendering" issue (when using `vimb` with `tabbed` as described in #138) by using `GTK2LIBS=gtk+-2.0 webkit-1.0`. I don't have access to that system anymore, and and cannot test this.

**Pull request merged**
